orderFood/orderFood/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('orderFoodApp.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orderFood/orderFoodApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('items/', views.items, name='items'),
    path('restDetail/<int:rid>', views.restDetail, name='restDetail'),
    path('itemsDetail/<int:fid>', views.itemsDetail, name='itemsDetail'),
    path('cart/', views.cart, name='cart'),
    path('search/', views.search, name='search'),
    path('addcart/<int:fid>', views.add_cart, name='addcart'),
    path('updateqty/<int:uval>/<int:fid>',views.updateqty,name='updateqty'),
    path('remove/<int:fid>', views.remove, name='remove'),
    path('checkout/', views.checkout, name='checkout'),
    path('makePayment/', views.makePayment, name='makePayment'),
    path('myOrders/', views.myOrders, name='myOrders'),
    path('book_table/', views.book_table, name='book_table'),
    path('bookedTable/', views.bookedTable, name='bookedTable'),
    path('cancelBooking/<int:bid>/', views.cancelBooking, name='cancelBooking'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('ratingList/', views.ratingList, name='ratingList'),
    path('vegList/', views.vegList, name='vegList'),
    path('deliveryTimeList/', views.deliveryTimeList, name='deliveryTimeList'),
]

orderFood/orderFoodApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django_otp.models import Device

# Create your models here.
class CustomManager(models.Manager):    
    def rating_list(self):
        return self.filter(F_rating__gte = "4.0")
    
    def veg_list(self):
        return self.filter(F_type__exact = "Veg")
    
    def deliveryTime_list(self):
        return super().get_queryset().order_by("F_dtime")
    

class FoodItems(models.Model):
    FI_id = models.IntegerField(primary_key=True)
    FI_name = models.CharField(max_length=25)
    FI_image = models.ImageField(upload_to="pics")


class FoodBrands(models.Model):
    FB_id = models.IntegerField(primary_key=True)
    FB_name = models.CharField(max_length=25)
    FB_dtime = models.CharField(max_length=25)
    FB_image = models.ImageField(upload_to="pics")

class Foods(models.Model):
    F_id = models.IntegerField(primary_key=True)
    F_name = models.CharField(max_length=25)
    F_dtime = models.CharField(max_length=25)
    F_rating = models.CharField(max_length=25)
    F_discount = models.CharField(max_length=25)
    F_price = models.IntegerField()
    F_speciality = models.CharField(max_length=50)
    F_type = models.CharField(max_length=50,choices=(('Veg','Veg'),('Non-Veg','Non-Veg')),default="Veg")
    F_image = models.ImageField(upload_to="pics")

    prod = CustomManager()
    objects=models.Manager()

class Restaurants(models.Model):
    R_id = models.IntegerField(primary_key=True)
    R_name = models.CharField(max_length=25)
    R_location = models.CharField(max_length=50,default=0)
    R_distance = models.CharField(max_length=25)
    R_rating = models.CharField(max_length=25)
    R_discount = models.CharField(max_length=25)
    R_price = models.IntegerField()
    R_speciality = models.CharField(max_length=50)
    R_type = models.CharField(max_length=50,choices=(('Veg','Veg'),('Non-Veg','Non-Veg')),default="Veg")
    R_image = models.ImageField(upload_to="pics")

class Booking(models.Model):
    restaurant = models.ForeignKey(Restaurants,on_delete = models.CASCADE,default=0)
    user = models.ForeignKey(User,on_delete = models.CASCADE,default=0)
    booking_id = models.IntegerField(primary_key=True,default=0)
    name = models.CharField(max_length=50)
    email = models.EmailField()
    phone_no = models.CharField(max_length=12)
    date = models.DateField()
    time = models.TimeField()
    people_size = models.IntegerField()

class CartItem(models.Model):
    product = models.ForeignKey(Foods,on_delete = models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    date_added = models.DateTimeField(auto_now_add = True)
    user = models.ForeignKey(User,on_delete = models.CASCADE, default=1)

class Checkout(models.Model):
    order_id = models.IntegerField()
    product = models.ForeignKey(Foods,on_delete = models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    date_added = models.DateTimeField(auto_now_add = True)
    user = models.ForeignKey(User,on_delete = models.CASCADE, default=1)
    is_completed = models.BooleanField(default=False)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

class UserOTPDevice(Device):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

orderFood/orderFoodApp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms  
from django.contrib.auth.models import User
from .models import Booking

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['restaurant', 'user', 'name', 'email', 'phone_no', 'date', 'time', 'people_size']

orderFood/orderFoodApp/views.py
import random
from django.db.models import Q
from django.shortcuts import render,redirect,HttpResponse
from .models import Foods,FoodBrands,FoodItems,Restaurants,CartItem,Checkout,Booking,User
from .forms import CreateUserForm
from .forms import BookingForm
from django.contrib.auth import login,logout,authenticate
from django.contrib import messages
import razorpay
# from django_otp.plugins.otp_totp.models import TOTPDevice
# from django_otp.plugins.otp_totp.util import random_hex

# Create your views here.
def index(req):
    return render(req,"index.html")

def items(req):
    food = Foods.objects.all()
    restaurant = Restaurants.objects.all()
    foodbrand = FoodBrands.objects.all()
    fooditem = FoodItems.objects.all()
    context = {'food':food,'foodbrand':foodbrand,'fooditem':fooditem,'restaurant':restaurant}
    return render(req,"items.html",context)

def vegList(req):
    queryset = Foods.prod.veg_list()
    foodbrand = FoodBrands.objects.all()
    fooditem = FoodItems.objects.all()
    context= {'food':queryset,'foodbrand':foodbrand,'fooditem':fooditem}
    return render(req,"items.html",context)

def deliveryTimeList(req):
    queryset = Foods.prod.deliveryTime_list()
    foodbrand = FoodBrands.objects.all()
    fooditem = FoodItems.objects.all()
    context= {'food':queryset,'foodbrand':foodbrand,'fooditem':fooditem}
    return render(req,"items.html",context)

def ratingList(req):
    queryset = Foods.prod.rating_list()
    foodbrand = FoodBrands.objects.all()
    fooditem = FoodItems.objects.all()
    context= {'food':queryset,'foodbrand':foodbrand,'fooditem':fooditem}
    return render(req,"items.html",context)

def itemsDetail(req,fid):
    food = Foods.objects.get(F_id = fid)
    context = {'food':food}
    return render(req,"itemsDetail.html",context)

def search(req):
    query = req.GET.get('q', '')

    # Check if the query matches any restaurants
    if Restaurants.objects.filter(R_name__icontains=query).exists() or Restaurants.objects.filter(R_location__icontains=query).exists():
        action = '/searchRestaurant/'
    else:
        action = '/searchFood/'

    # Perform the appropriate query based on the determined action
    if action == '/searchRestaurant/':
        result = Restaurants.objects.filter(
            Q(R_name__icontains=query) |
            Q(R_location__icontains=query)
        )
        return render(req, "searchRestaurant.html", {'results': result, 'query': query})
    else:
        result = Foods.objects.filter(
            Q(F_name__icontains=query) |
            Q(F_speciality__icontains=query) |
            Q(F_type__icontains=query)
        )
        return render(req, "searchFood.html", {'results': result, 'query': query})

def cart(req):
    if req.user.is_authenticated:
        allproducts = CartItem.objects.filter(user = req.user)
    else:
        return redirect("/login")
    context = {}
    context['cart_items'] = allproducts
    total_price=0
    for x in allproducts:
        total_price += (x.product.F_price * x.quantity)
    context['total'] = total_price
    length = len(allproducts)
    context['items'] = length
    return render(req,"cart.html",context)

def add_cart(req,fid):
    products = Foods.objects.get(F_id = fid)
    user = req.user if req.user.is_authenticated else None
    if user:
        cart_item,created = CartItem.objects.get_or_create(product = products,user=user) 
    else:
        return redirect("/login") 
        # cart_item,created = CartItem.objects.get_or_create(product = products) 
    if not created:
        cart_item.quantity += 1
    else:
        cart_item.quantity = 1
    cart_item.save()
    return redirect("/cart")

def updateqty(req,uval,fid):
    products = Foods.objects.get(F_id=fid)
    user = req.user
    c = CartItem.objects.filter(product=products,user=user)
    if uval == 1:
        a = c[0].quantity + 1
        c.update(quantity = a)
    else:
        a = c[0].quantity - 1
        c.update(quantity = a)
    return redirect("/cart")

def remove(req,fid):
    m = CartItem.objects.filter(product_id = fid)
    m.delete()
    return redirect("/cart")

def checkout(req):
    c = CartItem.objects.filter(user = req.user)
    context = {}
    context['cart_items'] = c
    total_price=0
    for x in c:
        total_price += (x.product.F_price * x.quantity)
    context['total'] = total_price
    length = len(c)
    context['items'] = length
    return render(req,"checkout.html",context)

def makePayment(req):
    c = CartItem.objects.filter(user = req.user)
    oid = random.randrange(1000,99999)
    for x in c:
        Checkout.objects.create(order_id = oid, product_id = x.product.F_id, user = req.user, quantity = x.quantity)
    orders = Checkout.objects.filter(user = req.user,is_completed=False)
    total_price=0
    for x in orders:
        total_price += (x.product.F_price * x.quantity)
        oid = x.order_id
    client = razorpay.Client(auth=("rzp_test_9r4EOeXGU6gUh9", "1OOx43XwALcea48VsFWTdZ9a"))
    data = {
    "amount": total_price*100,
    "currency": "INR",
    "receipt": "oid",
    }
    payment = client.order.create(data = data)
    context = {}
    context['data'] = payment
    context['amount'] = payment['amount']
    c.delete()
    orders.update(is_completed=True)
    return render(req,"payment.html",context)

def myOrders(req):
    myorder = Checkout.objects.filter(user = req.user,is_completed=True)
    context = {}
    context["myorder"] = myorder
    return render(req,"myorder.html",context)

def restDetail(req,rid):
    restaurant = Restaurants.objects.get(R_id = rid)
    context = {'restaurant':restaurant}
    return render(req,"restDetail.html",context)

def book_table(req):
    R_id = req.POST.get('restaurant')
    id = req.POST.get('user')
    if req.method == 'POST':
        form = BookingForm(req.POST)
        if form.is_valid():
            restaurant_id = req.POST.get('restaurant')
            user_id = req.POST.get('user')
            restaurant = Restaurants.objects.get(R_id=restaurant_id)
            user = User.objects.get(id=user_id)
            form.instance.restaurant = restaurant
            form.instance.user = user
            form.save()
            return redirect("/bookedTable")
    else:
        form = BookingForm()
    return render(req, 'bookTable.html', {'form': form, 'restaurant_id': R_id, 'user_id': id})

def bookedTable(req):
    booked_tables = Booking.objects.all()
    return render(req,"bookedTable.html",{"booked_tables":booked_tables})

def cancelBooking(req,bid):
    booking = Booking.objects.filter(booking_id=bid)
    booking.delete()
    return redirect("/bookedTable")

def register_user(req):
    form = CreateUserForm()
    if req.method == "POST":
        form = CreateUserForm(req.POST)
        if form.is_valid():
            form.save()
            messages.success(req,("User Created Successfully"))
            return redirect("/login")
        else:
            messages.error(req,"Incorrect Password Format")
    context = {'form':form}
    return render(req,"register.html",context)

# def generate_otp_key():
#     return random_hex(20)

# def enable_otp_user(user):
#     otp_key = generate_otp_key()
#     totp_device = TOTPDevice.objects.create(user=user,confirmed=True,key=otp_key)
#     return totp_device

def login_user(req):
    if req.method == 'POST':
        username = req.POST["username"]
        password = req.POST["password"]
        user = authenticate(req,username=username,password=password)
        if user is not None:
            login(req,user)
            messages.success(req,("You have been logged in!!"))
            return redirect("/")
        else:
           messages.error(req,"Incorrect username or Password")
           return redirect("/login") 
    else:
        return render(req,"login.html")
    
def logout_user(req):
    logout(req)
    messages.success(req,("You have logged out Successfully"))
    return redirect("/")

orderFood/orderFoodApp/templates/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}  {% endblock %}</title>
    <link rel="shortcut icon" href="https://tse2.mm.bing.net/th?id=OIP.ZnFQtmeCLNZ7Rd_m9Ba1xAHaHa&pid=Api&P=0&h=180" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <div class="container">       
        <div class="shadow p-3 mb-4 bg-body-tertiary rounded" style="display: flex;">
            <div class="container-logo">
                <a href="/"><img src="{% static 'images/icons/footerLogo.png' %}" style="width: 100px;
                    margin-top: 15px; margin-right: 15px;"></a>
            </div>
            <div class="search-container">
                <div class="detect-location" style="display: flex;">
                    <img src="{% static 'images/icons/location.png' %}" alt="">
                    <input type="text" placeholder="Mumbai">
                    <img src="{% static 'images/icons/down-arrow.png' %}" alt="">
                </div>
                <span style="padding: 7px;">|</span>
                <form id="search-form" class="d-flex" method="get" action="/search/">
                    {% csrf_token %}
                    <div class="search-item">
                        <img src="{% static 'images/icons/search.png' %}" style="width: 25px; height: fit-content; margin-top: 2px; position: absolute;">
                        <input id="search-input" type="search" name="q" placeholder="Search for restaurant, cuisine or a dish">
                        <button type="submit" class="btn btn-danger" style="position: absolute;
                        right: 400px;
                        margin-top: -6px;">Search</button>
                    </div>
                </form>                
            </div>
            <ul style="margin-left: -20px;gap: 20px;margin-top: 13px;">
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}"><strong>LogOut</strong></a></li>
                {% else %}
                <li><a href="{% url 'login' %}"><strong>LogIn</strong></a></li>
                {% endif %}
                <li><a href="{% url 'myOrders' %}"><strong>My Orders</strong></a></li>
                <li><a href="{% url 'cart' %}"><i class="bi bi-cart" style="font-size: 18px; font-weight:650;">Cart</i></a></li>
            </ul>
        </div>
        </div>  
    </header>

    {% block body %}

    {% endblock %}

    <footer class = "footer__container">
        <div class = "footer_section1">
            <img src = "{% static 'images/icons/footerLogo.png' %}" alt = "zomato logo" />
            <div class = "section1__button_container">
                <button>
                    <img src = "{% static 'images/items/indiaflag.png' %}" alt = "Indian Flag" style = "width: 16px; height: 16px" />
                    <select style = "border: none; background: #e8e8e8; cursor: pointer">
                        <option>India</option>
                        <option>United States</option>
                        <option>Australia</option>
                        <option>New Zealand</option>
                        <option>Spain</option>
                        <option>England</option>
                    </select>
                </button>
                <button>
                    <i class="bi bi-globe"></i>
                    <select style = "border: none; background: #e8e8e8; cursor: pointer">
                        <option>English</option>
                        <option>Español</option>
                        <option>Čeština</option>
                        <option>Slovenčina</option>
                        <option>Polish</option>
                        <option>Italian</option>
                    </select>
                </button>
            </div>
        </div>
        <div class = "navigation_container">
            <div class = "link_container">
                <h5>About Zomato</h5>
                <div class = "link_container_anchors">
                    <a href = "#">Who We Are</a>
                    <a href = "#">Blog</a>
                    <a href = "#">Work With Us</a>
                    <a href = "#">Investor Relations</a>
                    <a href = "#">Report Fraud</a>
                    <a href = "#">Contact Us</a>
                </div>
            </div>
            
            <div class = "link_container">
                <h5>Zomaverse</h5>
                <div class = "link_container_anchors">
                    <a href = "#">Zomato</a>
                    <a href = "#">Blinkit</a>
                    <a href = "#">Feeding India</a>
                    <a href = "#">Hyperpure</a>
                    <a href = "#">Zomaland</a>
                </div>
            </div>
            
            <div class = "link_container">
                <h5>For Restaurants</h5>
                <div class = "link_container_anchors">
                    <a href = "#">Partner With Us</a>
                    <a href = "#">Apps For You</a>
                </div>
                <h5 id = "enterprises">For Enterprises</h5>
                <div class = "link_container_anchors">
                    <a href = "#">Zomato For Work</a>
                </div>
            </div>
            
            <div class = "link_container">
                <h5>Learn More</h5>
                <div class = "link_container_anchors">
                    <a href = "#">Privacy</a>
                    <a href = "#">Security</a>
                    <a href = "#">Terms</a>
                    <a href = "#">Sitemap</a>
                </div>
            </div>
            
            <div class = "link_container">
                <h5>Social Links</h5>
                <div class = "social_media_icon_buttons">
                    <button role="button" href="https://twitter.com/"><i class="bi bi-twitter"></i></button>
                    <button role="button" href="https://www.google.com/"><i class="bi bi-google"></i></button>
                    <button role="button" href="https://instagram.com/"><i class="bi bi-instagram"></i></button>
                    <button role="button" href="https://linkedin.com/"><i class="bi bi-linkedin"></i></button>
                    <button role="button" href="https://github.com/"><i class="bi bi-github"></i></button>
                    <div class = "social_media_logos">
                        <img src = "{% static 'images/icons/appstore.png' %}" alt = "Apple store" />
                        <img src = "{% static 'images/icons/playstore.png' %}" alt = "Play store" id = "img2"/>
                    </div>
                </div>
            </div>
        </div>
        <div class = "disclaimer">
        IT-Vedant | 2024 © Zomato™ Ltd. All rights reserved.
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#search-form').submit(function(event) {
                event.preventDefault(); // Prevent default form submission

                var query = $('#search-input').val().trim();

                // Submit the form with the query string to your Django view
                window.location.href = '/search/?q=' + encodeURIComponent(query);
            });
        });
    </script>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

orderFood/orderFoodApp/templates/bookTable.html
{% extends 'base2.html' %} 
{% load static %} 
{% block title %} Best Restaurants in India - Zomato {% endblock %} 
{% block body %}
<div class="container">
    <a href="javascript:history.go(-1)"><i class="bi bi-arrow-left"></i></a>
    <center>
        <div class="bookTable" data-aos="fade-up">
            <div id="book-a-table" class="book-a-table">
                <h2 class="text-danger">Book A Table</h2>
                <form method="post" role="form">
                    {% csrf_token %}
                    
                    <div class="form-group">
                        <label for="id_restaurant">Restaurant:</label>
                        {{ form.restaurant }}
                    </div>
                    
                    <div class="form-group">
                        <label for="id_user">User:</label>
                        {{ form.user }}
                    </div>
                    
                    <div class="form-group">
                        <label for="id_name">Your Name:</label>
                        {{ form.name }}
                    </div>
                    
                    <div class="form-group">
                        <label for="id_email">Your Email:</label>
                        {{ form.email }}
                    </div>
                    
                    <div class="form-group">
                        <label for="id_phone_no">Your Phone:</label>
                        {{ form.phone_no }}
                    </div>
                    
                    <div class="form-group">
                        <label for="id_date">Date:</label>
                        {{ form.date }}
                    </div>
                    
                    <div class="form-group">
                        <label for="id_time">Time:</label>
                        {{ form.time }}
                    </div>
                    
                    <div class="form-group">
                        <label for="id_people_size">No. of People:</label>
                        {{ form.people_size }}
                    </div>
                    
                    <button type="submit" class="btn btn-danger float-right m-3">Book Now </button>
                </form>
                
            </div>
        </div>
    </center>
</div>
{% endblock %}

orderFood/orderFoodApp/templates/bookedTable.html
{% extends 'base2.html' %} 
{% load static %} 
{% block title %} Best Restaurants in India - Zomato {% endblock %} 
{% block body %} 
    <style>
        h2 {
            color: #333;
            text-align: center;
            margin-top: 20px;
        }

        table {
            width: 80%;
            margin: 20px auto;
            border-collapse: collapse;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);
        }

        th, td {
            padding: 15px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #333;
            color: #fff;
        }

        tr:hover {
            background-color: #f5f5f5;
        }

        .restaurant {
            font-style: italic;
            color: #888;
        }
    </style>

<div class="container">
    <a href="javascript:history.go(-1)"><i class="bi bi-arrow-left"></i></a>
    <h2>Booked Tables</h2>
    {% for booking in booked_tables %}
        <table>
            <thead>
                <tr>
                    <th>Restaurant</th>
                    <th>User</th>
                    <th>Name</th>
                    <th>Date</th>
                    <th>Time</th>
                    <th>No. of People</th>
                    <th>Cancel Booking</th>
                </tr>
            </thead>
            <tbody>
                    <tr>
                        <td>{{ booking.restaurant.R_name }}</td>
                        <td>{{ booking.user }}</td>
                        <td>{{ booking.name }}</td>
                        <td>{{ booking.date }}</td>
                        <td>{{ booking.time }}</td>
                        <td>{{ booking.people_size }}</td>
                        <td>
                            <form action="{% url 'cancelBooking' booking.booking_id %}" method="post">
                                {% csrf_token %}
                                <button type="submit">Cancel</button>
                            </form>
                        </td>
                    </tr>                            
            </tbody>
        </table>
        {% empty %}        
        <p class="text-center" >No Tables have been booked.</p>
    {% endfor %}
</div>
{% endblock %}

orderFood/orderFoodApp/templates/cart.html
{% extends 'base2.html' %} 
{% load static %} 
{% block title %} Best Restaurants in India - Zomato {% endblock %} 
{% block body %} 

<div class="container">
    
    <a href="javascript:history.go(-1)"><i class="bi bi-arrow-left"></i></a> <h2 class="mt-1 mb-4">Food Cart</h2> 
    
    <!-- Cart Items -->
    {% for x in cart_items %}
    <div class="cart-item m-3">
        <div class="row">
            <div class="col-md-2">
                <img src="{{x.product.F_image.url}}" alt="Food Image 1" class="img-fluid">
            </div>
            <div class="col-md-2">
                <h5>{{x.product.F_name}}</h5>
                <p>{{x.product.F_speciality}}</p>
            </div>
            <div class="col-md-2">
                <p>&#x20b9; {{x.product.F_price}} per one</p>
            </div>
            <div class="col-md-2 m-3">
                <p class="d-flex">
                    <a href="/updateqty/0/{{x.product.F_id}}"><button class="btn btn-danger m-2">-</button></a>
                    <input type="number" value="{{x.quantity}}" style="width: 50px; height: 40px; margin-top: 6px;">
                    <a href="/updateqty/1/{{x.product.F_id}}"><button class="btn btn-danger m-2">+</button></a>
                </p>
            </div>
            <div class="col-md-2 m-3">
                <a href="/remove/{{x.product.F_id}}"><button type="button" class="btn btn-danger m-2">Remove</button></a>
            </div>
        </div>
    </div>
    {% empty %}
    <div class="row">
        <div class="col text-center">
            Your Food Cart is Empty. <br>
            Order Your Foods Fast. <br>
        </div>
    </div>
    {% endfor %}

    <!-- Total Amount -->
    <div class="total-amount text-right m-3">
        <p><strong>Total: </strong><i>Rs.{{total}}</i></p>
    </div>

    <!-- Checkout Button -->
    <div class="text-right m-3">
        <a href="/checkout" class="btn btn-danger">Proceed to Checkout</a>
    </div>
    
</div>

{% endblock %}

orderFood/orderFoodApp/templates/checkout.html
{% extends 'base2.html' %} 
{% load static %} 
{% block title %} Best Restaurants in India - Zomato {% endblock %} 
{% block body %} 

<div class="container">
    
    <a href="javascript:history.go(-1)"><i class="bi bi-arrow-left"></i></a> 
    <h2 class="mt-1 mb-4">Checkout</h2>    
    <!-- Cart Items -->
    {% for x in cart_items %}
    <div class="cart-item m-3">
        <div class="row">
            <div class="col-md-2">
                <img src="{{x.product.F_image.url}}" alt="Food Image 1" class="img-fluid">
            </div>
            <div class="col-md-3">
                <h5>{{x.product.F_name}}</h5>
                <p>{{x.product.F_speciality}}</p>
            </div>
            <div class="col-md-3 m-3">
                <p>&#x20b9; {{x.product.F_price}} per one</p>
            </div>
            <div class="col-md-3 m-3">
                <p><b>Quantity:</b>&nbsp;&nbsp;{{x.quantity}}</p>
            </div>
        </div>
    </div>
    {% empty %}
    <div class="row">
        <div class="col">
            Your Food Cart is Empty. <br>
            Order Your Foods Fast. <br>
        </div>
    </div>
    {% endfor %}

    <div class="info-pay" style="display: flex;
    justify-content: space-between;">
        <div class="text-right m-3">
            <p><strong>Total: </strong><i>Rs.{{total}}</i></p>
            <a href="/makePayment" class="btn btn-danger">Proceed to Pay</a>
        </div>
    </div>
    
    
</div>

{% endblock %}

orderFood/orderFoodApp/templates/itemsDetail.html
{% extends 'base2.html' %} 
{% load static %} 
{% block title %} Best Restaurants in India - Zomato {% endblock %} 
{% block body %}  
  <div class="container">

    <div class="row mt-4">
        <a href="javascript:history.go(-1)"><i class="bi bi-arrow-left"></i></a>
        <!-- Food Item Details -->
        <div class="col-lg-8">
            <h2 class="mb-4">{{food.F_name}}</h2>

            <!-- Image Gallery -->
            <div class="gallery">
                <img src="{{food.F_image.url}}" alt="Food Image 1" style="width: 100%; height: 400px; margin-bottom: 10px;">
            </div>         
        </div>

        <!-- Sidebar with Additional Information -->
        <div class="col-lg-4 mt-5">
             <!-- Nutritional Information -->
             <h4 class="mt-4">Nutritional Information</h4>
             <ul>
                 <li>Calories: 300</li>
                 <li>Protein: 20g</li>
                 <li>Carbohydrates: 40g</li>
                 <li>Fat: 10g</li>
             </ul>

            <h4 class="mb-4">Additional Information</h4>
            <p><strong>Price:</strong> &#x20b9; {{food.F_price}} per one</p>
            <p><strong>Availability:</strong> In Stock</p>
            <p><strong>Speciality:</strong> {{food.F_speciality}}</p>

            <!-- Call to Action Button -->
            <a href="/addcart/{{food.F_id}}" class="btn btn-danger btn-block mt-4">Add to Cart</a>
            <a href="/items"><button type="button" class="btn btn-danger btn-block mt-4">Back</button></a>
        </div>
    </div>
    <!-- /.row -->

</div>
{% endblock %}